# Generated by Django 3.2.13 on 2024-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_alter_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
                
        migrations.AlterField(
            model_name='staff',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),

    ]
